query CoolStory($owner: String!, $repo: String!) {
  repository(owner: $owner, name: $repo) {
    nameWithOwner
    description
    descriptionHTML
    homepageUrl
    isFork
    forkCount
    licenseInfo {
      name
    }
    createdAt
    pushedAt

    # package.json
    object:packageJSON(expression: "master:package.json") {
      ...on Blob {
        text
      }
    }

    # app/package.json 
    # for electron-builder apps with two package.json files
    # https://www.electron.build/tutorials/two-package-structure
    object:appDirPackageJSON(expression: "master:app/package.json") {
      ...on Blob {
        text
      }
    }

    # releases
    releases(first: 5, orderBy: { field: CREATED_AT, direction: DESC }) {
      edges {
        node {
          name
          createdAt
          isDraft
          isPrerelease
          publishedAt
          tag {
            name
          }
          releaseAssets(first: 100) {
            edges {
              node {
                name
                downloadCount
                downloadUrl
                size
              }
            }
          }
        }
      }
      pageInfo {
        endCursor
        hasNextPage
      }
    }

    #collaborators
     collaborators(affiliation: DIRECT, first: 100){
        nodes{
          name
          avatarUrl
          bio
          company
          contributedRepositories(first:100, orderBy:{field:UPDATED_AT, direction:DESC}){
            nodes{
              nameWithOwner
            }
          }
        }
      }

  }
}
